from .account import AccountSchema
from .accountLog import AccountLogSchema
from .dept import DeptSchema
from .accountRole import AccountRoleSchema
from .menu import MenuSchema
from .role import RoleSchema
from .roleMenu import RoleMenuSchema
from .dictType import DictTypeSchema
from .dictData import DictDataSchema
